### ISSUE TITLE
Example for open interface constructors doesn’t compile

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#100]
(Probably connected with the previous issue #99)

This issue possibly is connected with the open item "Open Shortcalling" on the Roadmap for Interfaces, but since it is shown above Planned Features I assumed it should work:

In the Guide, https://vale.dev/guide/interfaces, section: Open Interface Constructors, the accompanying code snippet does not compile after removing the ... :

```
interface Bipedal {
  fn hop(s &Human) void;
  fn skip(s &Human) void;
}

struct Human {  }
fn hop(s &Human) {  }
fn skip(s &Human) {  }
impl Bipedal for Human;

fn hopscotch(s &Bipedal) {
  s.hop();
  s.skip();
  s.hop();
}

fn main() export {
   x = Bipedal(
    { println("Hop!"); },
    { println("Skip!"); });
  // x is an unnamed substruct which implements Bipedal.

  hopscotch(&x);
}
```
The compiler error is:

Exception in thread "main" java.util.NoSuchElementException: key not found: InterfaceRef2(FullName2(List(),CitizenName2(Bipedal,List())))
        at scala.collection.MapLike.default(MapLike.scala:235)
        at scala.collection.MapLike.default$(MapLike.scala:234)
        at scala.collection.AbstractMap.default(Map.scala:63)
        at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
        at net.verdagon.vale.templar.Temputs.lookupInterface(Temputs.scala:244)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.$anonfun$maakeStruct$3(StructTemplarCore.scala:129)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.$anonfun$maakeStruct$3$adapted(StructTemplarCore.scala:127)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:181)
....

Again it is strange that interface Bipedal should depend on Human.
The println("Hop!"); lambda for the unnamed substruct x cannot possibly implement the signature fn hop(s &Human) void ?

**Comment by Ivo-Balbaert** [comment]
The new example with interface IShip sadly doesn't compile either for me:

Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast open_interfaces2.vale

internal(-13337) Conflict in determining ordinary rules' runes: InferSolveFailure(Map(ImplicitRune2(CitizenTemplateName2(IShip,0:0),0) -> MutabilityTemplataType, CodeRune2(Functor0) -> CoordTemplataType, AnonymousSubstructParentInterfaceRune2() -> KindTemplataType),Map(),None,Inferences(Map(ImplicitRune2(CitizenTemplateName2(IShip,0:0),0) -> MutabilityTemplataType, CodeRune2(Functor0) -> CoordTemplataType, AnonymousSubstructParentInterfaceRune2() -> KindTemplataType),Map(ImplicitRune2(CitizenTemplateName2(IShip,0:0),0) -> MutabilityTemplata(Mutable), AnonymousSubstructParentInterfaceRune2() -> KindTemplata(InterfaceRef2(FullName2(List(),CitizenName2(IShip,List()))))),Map()),RangeS(CodeLocationS(-13337,0),CodeLocationS(-13337,0)),Not enough to solve! Couldn't figure out: Set(CodeRune2(Functor0)),List())

Also the text of the last § doesn't apply to the new example: "In this example, we're giving it a lambda for its hop method, and another lambda for its skip method."

**Comment by Verdagon** [comment]
Fixed this in the compiler! And figured out why the automatic sample-runner didn't catch this.

Will close this on next release. Thanks for finding this, Ivo!

**Comment by Ivo-Balbaert** [comment]
Thanks!
