### ISSUE TITLE
Type-checker doesn't like arrays

### ISSUE THREAD

**Issue by F0x1fy** [ValeLang/Vale#109]
Defining an array within a struct like so:
```
data Array <T>;
```
will cause the error `Expected 2 template args but received 1`.

I tried making it `<NT, T>` just to see, and it gave a very scary looking error!
```
Exception in thread "main" java.lang.RuntimeException: RuleTyperSolveFailure(ConclusionsBox(Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType))),RangeS(CodeLocationS(0,0),CodeLocationS(0,136)),Failed during pre-solving!,List(RuleTyperSolveFailure(ConclusionsBox(Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType))),RangeS(CodeLocationS(0,0),CodeLocationS(0,136)),,List(RuleTyperEvaluateConflict(Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType)),RangeS(CodeLocationS(0,53),CodeLocationS(0,74)),Failed evaluating right rule!,Some(RuleTyperEvaluateConflict(Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType)),RangeS(CodeLocationS(0,58),CodeLocationS(0,73)),,Some(RuleTyperEvaluateConflict(Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType)),RangeS(CodeLocationS(0,58),CodeLocationS(0,73)),Conflict while matching param #1! Was matching CoordTemplataType and RuneST(RangeS(CodeLocationS(0,70),CodeLocationS(0,72)),CodeRuneS(NT)),Some(RuleTyperMatchConflict#(Conflict in rune!, List(RuleTyperMatchConflict#(Disagreement about rune CodeRuneA(NT)! MutabilityTemplataType and CoordTemplataType, List(), Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType)))), Conclusions(Map(MemberRuneA(0) -> CoordTemplataType, CodeRuneA(NT) -> MutabilityTemplataType, CodeRuneA(T) -> CoordTemplataType, MemberRuneA(1) -> CoordTemplataType)))))))))))))
	at net.verdagon.vale.vfail$.apply(vassert.scala:65)
	at net.verdagon.vale.astronomer.Astronomer$.translateStruct(Astronomer.scala:298)
	at net.verdagon.vale.astronomer.Astronomer$.$anonfun$translateProgram$1(Astronomer.scala:660)
	at scala.collection.immutable.List.map(List.scala:283)
	at net.verdagon.vale.astronomer.Astronomer$.translateProgram(Astronomer.scala:660)
	at net.verdagon.vale.astronomer.Astronomer$.runAstronomer(Astronomer.scala:696)
	at net.verdagon.vale.driver.Driver$.build(Driver.scala:149)
	at net.verdagon.vale.driver.Driver$.build(Driver.scala:89)
	at net.verdagon.vale.driver.Driver$.buildAndOutput(Driver.scala:179)
	at net.verdagon.vale.driver.Driver$.main(Driver.scala:259)
	at net.verdagon.vale.driver.Driver.main(Driver.scala)
```
Full struct:
```
struct Sprawl <T, NT> {
    data Array <T>;

    dims Array <mut, NT>;
    offs Array <mut, NT>;

    cached_dims Array <mut, NT>;
}
```

**Comment by Verdagon** [comment]
The first compiler problem here is that there's no humanized error for this, definitely.

I want to also figure out what you're trying to do, to see if we can phrase the error message in a way that steers you in the right direction. What are T and NT in this example?

**Comment by F0x1fy** [comment]
`T` is the value type (elements) in the Sprawl and `NT` (number type) is the indexing type.

**Comment by F0x1fy** [comment]
Closed -- Made a typo by forgetting `mut` in `<mut, T>`
