### ISSUE TITLE
Space after each/eachI

### ISSUE THREAD

**Issue by divinusdracodominus** [ValeLang/Vale#241]
Exception in thread "main" java.lang.RuntimeException: wat: ./src/main.vale:4:5: Parse error somewhere inside this each/eachI. Imprecise inner error: ./src/main.vale:4:5: Internal parser error: '{' expected but ' ' found:
each (&vals) (element) {

	at net.verdagon.vale.vfail$.apply(vassert.scala:65)
	at net.verdagon.vale.vwat$.apply(vassert.scala:77)
	at net.verdagon.vale.parser.ParserCompilation$.$anonfun$loadAndParseIteration$11(Parser.scala:719)
	at net.verdagon.vale.FileCoordinateMap.$anonfun$map$3(CodeHierarchy.scala:101)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.verdagon.vale.FileCoordinateMap.$anonfun$map$2(CodeHierarchy.scala:100)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:125)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.verdagon.vale.FileCoordinateMap.$anonfun$map$1(CodeHierarchy.scala:98)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:156)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at net.verdagon.vale.FileCoordinateMap.map(CodeHierarchy.scala:96)
	at net.verdagon.vale.parser.ParserCompilation$.loadAndParseIteration(Parser.scala:716)
	at net.verdagon.vale.parser.ParserCompilation$.loadAndParse(Parser.scala:674)
	at net.verdagon.vale.parser.ParserCompilation.getParseds(Parser.scala:756)
	at net.verdagon.vale.parser.ParserCompilation.getCodeMap(Parser.scala:747)
	at net.verdagon.vale.scout.ScoutCompilation.getCodeMap(Scout.scala:411)
	at net.verdagon.vale.astronomer.AstronomerCompilation.getCodeMap(Astronomer.scala:788)
	at net.verdagon.vale.templar.TemplarCompilation.getCodeMap(TemplarCompilation.scala:28)
	at net.verdagon.vale.hammer.HammerCompilation.getCodeMap(HammerCompilation.scala:37)
	at net.verdagon.vale.driver.FullCompilation.getCodeMap(FullCompilation.scala:40)
	at net.verdagon.vale.driver.Driver$.build(Driver.scala:311)
	at net.verdagon.vale.driver.Driver$.buildAndOutput(Driver.scala:385)
	at net.verdagon.vale.driver.Driver$.main(Driver.scala:483)
	at net.verdagon.vale.driver.Driver.main(Driver.scala)

**Comment by Verdagon** [comment]
Dup of #108
