### ISSUE TITLE
Example for using interfaces doesn’t compile

### ISSUE THREAD

**Issue by Ivo-Balbaert** [ValeLang/Vale#99]
In the Guide, https://vale.dev/guide/interfaces, section: Using Interfaces, the accompanying code snippet does not compile after removing the ...   :

interface Bipedal {
  fn hop(s &Human) void;
  fn skip(s &Human) void;
}

struct Human {  }
fn hop(s &Human) {  }
fn skip(s &Human) {  }
impl Bipedal for Human;

fn hopscotch(s &Bipedal) {
  s.hop();
  s.skip();
  s.hop();
}

struct DarkElf {  }
fn hop(s &DarkElf) {  }
fn skip(s &DarkElf) {  }
impl DarkElf for Bipedal;  //  (1) <--

fn main() export {
  wulfgar = Human();
  hopscotch(&wulfgar);
  drizzt = DarkElf();
  hopscotch(&drizzt);
}

Line (1) is a typo, this should be: **impl Bipedal for DarkElf** 

After changing that, we still get a compile error:

>python ..\valec.py using_interfaces.vale
Valestrom path: C:\Vale
Builtins path: C:\Vale\builtins
No VALEC_PATH in env, assuming the one in current directory.
valec path: C:\Vale\Midas.exe
Using Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\.
Running: java -cp C:\Vale\Valestrom.jar net.verdagon.vale.driver.Driver build -o build.vast using_interfaces.vale C:\Vale\builtins\arrayutils.vale C:\Vale\builtins\castutils.vale C:\Vale\builtins\file.vale C:\Vale\builtins\opt.vale C:\Vale\builtins\printutils.vale C:\Vale\builtins\strings.vale C:\Vale\builtins\utils.vale
Internal error while compiling [PureWindowsPath('using_interfaces.vale'), PureWindowsPath('C:/Vale/builtins/arrayutils.vale'), PureWindowsPath('C:/Vale/builtins/castutils.vale'), PureWindowsPath('C:/Vale/builtins/file.vale'), PureWindowsPath('C:/Vale/builtins/opt.vale'), PureWindowsPath('C:/Vale/builtins/printutils.vale'), PureWindowsPath('C:/Vale/builtins/strings.vale'), PureWindowsPath('C:/Vale/builtins/utils.vale')]:

Exception in thread "main" java.lang.RuntimeException: Assertion failed!
        at net.verdagon.vale.vfail$.apply(vassert.scala:65)
        at net.verdagon.vale.vassert$.apply(vassert.scala:30)
        at net.verdagon.vale.vassert$.apply(vassert.scala:26)
        at net.verdagon.vale.templar.function.FunctionTemplarCore.makeInterfaceFunction(FunctionTemplarCore.scala:236)
        at net.verdagon.vale.templar.function.FunctionTemplarCore.evaluateFunctionForHeader(FunctionTemplarCore.scala:106)
        at net.verdagon.vale.templar.function.FunctionTemplarMiddleLayer.getOrEvaluateFunctionForHeader(FunctionTemplarMiddleLayer.scala:163)
        at net.verdagon.vale.templar.function.FunctionTemplarOrdinaryOrTemplatedLayer.evaluateOrdinaryFunctionFromNonCallForHeader(FunctionTemplarOrdinaryOrTemplatedLayer.scala:265)
        at net.verdagon.vale.templar.function.FunctionTemplarClosureOrLightLayer.evaluateOrdinaryLightFunctionFromNonCallForHeader(FunctionTemplarClosureOrLightLayer.scala:140)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryLightFunctionFromNonCallForHeader(FunctionTemplar.scala:346)
        at net.verdagon.vale.templar.function.FunctionTemplar.$anonfun$evaluateOrdinaryFunctionFromNonCallForHeader$1(FunctionTemplar.scala:151)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryFunctionFromNonCallForHeader(FunctionTemplar.scala:147)
        at net.verdagon.vale.templar.Templar$$anon$7.evaluateOrdinaryFunctionFromNonCallForHeader(Templar.scala:313)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.$anonfun$makeInterface$3(StructTemplarCore.scala:197)
        at scala.collection.immutable.List.map(List.scala:286)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.makeInterface(StructTemplarCore.scala:191)
        at net.verdagon.vale.templar.citizen.StructTemplarMiddle.getInterfaceRef(StructTemplarMiddle.scala:70)
        at net.verdagon.vale.templar.citizen.StructTemplarTemplateArgsLayer.$anonfun$getInterfaceRef$2(StructTemplarTemplateArgsLayer.scala:161)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.citizen.StructTemplarTemplateArgsLayer.getInterfaceRef(StructTemplarTemplateArgsLayer.scala:107)
        at net.verdagon.vale.templar.citizen.StructTemplar.getInterfaceRef(StructTemplar.scala:230)
        at net.verdagon.vale.templar.Templar$$anon$5.$anonfun$evaluateInterfaceTemplata$1(Templar.scala:209)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.Templar$$anon$5.evaluateInterfaceTemplata(Templar.scala:208)
        at net.verdagon.vale.templar.Templar$$anon$5.evaluateInterfaceTemplata(Templar.scala:132)
        at net.verdagon.vale.templar.infer.Inferer$$anon$1.evaluateInterfaceTemplata(Inferer.scala:130)
        at net.verdagon.vale.templar.templata.TemplataTemplarInner.coerce(TemplataTemplarInner.scala:527)
        at net.verdagon.vale.templar.templata.TemplataTemplarInner.lookupTemplata(TemplataTemplarInner.scala:489)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateTemplex(InfererEvaluator.scala:648)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateRule(InfererEvaluator.scala:425)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateEqualsRule(InfererEvaluator.scala:918)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateRule(InfererEvaluator.scala:421)
        at net.verdagon.vale.templar.infer.InfererEvaluator.$anonfun$solveUntilSettled$1(InfererEvaluator.scala:332)
        at net.verdagon.vale.templar.infer.InfererEvaluator.$anonfun$solveUntilSettled$1$adapted(InfererEvaluator.scala:330)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:89)
        at net.verdagon.vale.templar.infer.InfererEvaluator.solveUntilSettled(InfererEvaluator.scala:330)
        at net.verdagon.vale.templar.infer.InfererEvaluator.solve(InfererEvaluator.scala:81)
        at net.verdagon.vale.templar.infer.Inferer$.solve(Inferer.scala:103)
        at net.verdagon.vale.templar.InferTemplar.$anonfun$solve$1(InferTemplar.scala:45)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.InferTemplar.solve(InferTemplar.scala:32)
        at net.verdagon.vale.templar.InferTemplar.$anonfun$inferFromExplicitTemplateArgs$1(InferTemplar.scala:102)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.InferTemplar.inferFromExplicitTemplateArgs(InferTemplar.scala:87)
        at net.verdagon.vale.templar.citizen.AncestorHelper.$anonfun$getMaybeImplementedInterface$1(ImplTemplar.scala:55)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.citizen.AncestorHelper.getMaybeImplementedInterface(ImplTemplar.scala:44)
        at net.verdagon.vale.templar.citizen.AncestorHelper.$anonfun$getParentInterfaces$1(ImplTemplar.scala:95)
        at scala.collection.immutable.List.flatMap(List.scala:338)
        at net.verdagon.vale.templar.citizen.AncestorHelper.getParentInterfaces(ImplTemplar.scala:94)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.$anonfun$maakeStruct$1(StructTemplarCore.scala:93)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.citizen.StructTemplarCore.maakeStruct(StructTemplarCore.scala:91)
        at net.verdagon.vale.templar.citizen.StructTemplarMiddle.getStructRef(StructTemplarMiddle.scala:50)
        at net.verdagon.vale.templar.citizen.StructTemplarTemplateArgsLayer.$anonfun$getStructRef$2(StructTemplarTemplateArgsLayer.scala:95)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.citizen.StructTemplarTemplateArgsLayer.getStructRef(StructTemplarTemplateArgsLayer.scala:43)
        at net.verdagon.vale.templar.citizen.StructTemplar.$anonfun$getStructRef$1(StructTemplar.scala:216)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.citizen.StructTemplar.getStructRef(StructTemplar.scala:214)
        at net.verdagon.vale.templar.Templar$$anon$5.$anonfun$evaluateStructTemplata$1(Templar.scala:220)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.Templar$$anon$5.evaluateStructTemplata(Templar.scala:219)
        at net.verdagon.vale.templar.Templar$$anon$5.evaluateStructTemplata(Templar.scala:132)
        at net.verdagon.vale.templar.infer.Inferer$$anon$1.evaluateStructTemplata(Inferer.scala:134)
        at net.verdagon.vale.templar.templata.TemplataTemplarInner.coerce(TemplataTemplarInner.scala:540)
        at net.verdagon.vale.templar.templata.TemplataTemplarInner.lookupTemplata(TemplataTemplarInner.scala:478)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateTemplex(InfererEvaluator.scala:653)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateRule(InfererEvaluator.scala:425)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateEqualsRule(InfererEvaluator.scala:918)
        at net.verdagon.vale.templar.infer.InfererEvaluator.evaluateRule(InfererEvaluator.scala:421)
        at net.verdagon.vale.templar.infer.InfererEvaluator.$anonfun$solveUntilSettled$1(InfererEvaluator.scala:332)
        at net.verdagon.vale.templar.infer.InfererEvaluator.$anonfun$solveUntilSettled$1$adapted(InfererEvaluator.scala:330)
        at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
        at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
        at scala.collection.immutable.List.foldLeft(List.scala:89)
        at net.verdagon.vale.templar.infer.InfererEvaluator.solveUntilSettled(InfererEvaluator.scala:330)
        at net.verdagon.vale.templar.infer.InfererEvaluator.solve(InfererEvaluator.scala:81)
        at net.verdagon.vale.templar.infer.Inferer$.solve(Inferer.scala:103)
        at net.verdagon.vale.templar.InferTemplar.$anonfun$solve$1(InferTemplar.scala:45)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.InferTemplar.solve(InferTemplar.scala:32)
        at net.verdagon.vale.templar.InferTemplar.$anonfun$inferOrdinaryRules$1(InferTemplar.scala:64)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.InferTemplar.inferOrdinaryRules(InferTemplar.scala:63)
        at net.verdagon.vale.templar.function.FunctionTemplarOrdinaryOrTemplatedLayer.evaluateOrdinaryFunctionFromNonCallForBanner(FunctionTemplarOrdinaryOrTemplatedLayer.scala:68)
        at net.verdagon.vale.templar.function.FunctionTemplarClosureOrLightLayer.evaluateOrdinaryLightFunctionFromNonCallForBanner(FunctionTemplarClosureOrLightLayer.scala:59)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryLightFunctionFromNonCallForBanner(FunctionTemplar.scala:237)
        at net.verdagon.vale.templar.function.FunctionTemplar.$anonfun$evaluateOrdinaryFunctionFromNonCallForBanner$1(FunctionTemplar.scala:210)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryFunctionFromNonCallForBanner(FunctionTemplar.scala:206)
        at net.verdagon.vale.templar.OverloadTemplar.$anonfun$getCandidateBanners$1(OverloadTemplar.scala:349)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:160)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:160)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:97)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:160)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:158)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
        at net.verdagon.vale.templar.OverloadTemplar.getCandidateBanners(OverloadTemplar.scala:197)
        at net.verdagon.vale.templar.OverloadTemplar.$anonfun$scoutPotentialFunction$1(OverloadTemplar.scala:424)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.OverloadTemplar.scoutPotentialFunction(OverloadTemplar.scala:422)
        at net.verdagon.vale.templar.OverloadTemplar.scoutMaybeFunctionForPrototype(OverloadTemplar.scala:83)
        at net.verdagon.vale.templar.OverloadTemplar.scoutExpectedFunctionForPrototype(OverloadTemplar.scala:108)
        at net.verdagon.vale.templar.CallTemplar.evaluateNamedCall(CallTemplar.scala:140)
        at net.verdagon.vale.templar.CallTemplar.evaluateNamedPrefixCall(CallTemplar.scala:291)
        at net.verdagon.vale.templar.ExpressionTemplar.$anonfun$evaluate$1(ExpressionTemplar.scala:366)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.ExpressionTemplar.evaluate(ExpressionTemplar.scala:328)
        at net.verdagon.vale.templar.ExpressionTemplar.evaluateAndCoerceToReferenceExpression(ExpressionTemplar.scala:287)
        at net.verdagon.vale.templar.ExpressionTemplar.$anonfun$evaluate$1(ExpressionTemplar.scala:757)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.ExpressionTemplar.evaluate(ExpressionTemplar.scala:328)
        at net.verdagon.vale.templar.ExpressionTemplar.evaluateAndCoerceToReferenceExpression(ExpressionTemplar.scala:287)
        at net.verdagon.vale.templar.ExpressionTemplar$$anon$1.evaluateAndCoerceToReferenceExpression(ExpressionTemplar.scala:60)
        at net.verdagon.vale.templar.BlockTemplar.evaluateBlockStatementsInner(BlockTemplar.scala:142)
        at net.verdagon.vale.templar.BlockTemplar.evaluateBlockStatements(BlockTemplar.scala:59)
        at net.verdagon.vale.templar.ExpressionTemplar.evaluateBlockStatements(ExpressionTemplar.scala:1108)
        at net.verdagon.vale.templar.Templar$$anon$8.evaluateBlockStatements(Templar.scala:343)
        at net.verdagon.vale.templar.function.FunctionTemplarCore$$anon$1.evaluateBlockStatements(FunctionTemplarCore.scala:24)
        at net.verdagon.vale.templar.function.BodyTemplar.evaluateFunctionBody(BodyTemplar.scala:143)
        at net.verdagon.vale.templar.function.BodyTemplar.$anonfun$declareAndEvaluateFunctionBody$1(BodyTemplar.scala:97)
        at net.verdagon.vale.NullProfiler.childFrame(Profiler.scala:18)
        at net.verdagon.vale.templar.function.BodyTemplar.declareAndEvaluateFunctionBody(BodyTemplar.scala:51)
        at net.verdagon.vale.templar.function.FunctionTemplarCore.evaluateFunctionForHeader(FunctionTemplarCore.scala:59)
        at net.verdagon.vale.templar.function.FunctionTemplarMiddleLayer.getOrEvaluateFunctionForPrototype(FunctionTemplarMiddleLayer.scala:218)
        at net.verdagon.vale.templar.function.FunctionTemplarOrdinaryOrTemplatedLayer.evaluateOrdinaryFunctionFromNonCallForPrototype(FunctionTemplarOrdinaryOrTemplatedLayer.scala:288)
        at net.verdagon.vale.templar.function.FunctionTemplarClosureOrLightLayer.evaluateOrdinaryLightFunctionFromNonCallForPrototype(FunctionTemplarClosureOrLightLayer.scala:158)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryLightFunctionFromNonCallForPrototype(FunctionTemplar.scala:336)
        at net.verdagon.vale.templar.function.FunctionTemplar.$anonfun$evaluateOrdinaryFunctionFromNonCallForPrototype$1(FunctionTemplar.scala:178)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.function.FunctionTemplar.evaluateOrdinaryFunctionFromNonCallForPrototype(FunctionTemplar.scala:174)
        at net.verdagon.vale.templar.Templar.$anonfun$evaluate$8(Templar.scala:468)
        at net.verdagon.vale.templar.Templar.$anonfun$evaluate$8$adapted(Templar.scala:460)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at net.verdagon.vale.templar.Templar.$anonfun$evaluate$1(Templar.scala:460)
        at net.verdagon.vale.NullProfiler.newProfile(Profiler.scala:17)
        at net.verdagon.vale.templar.Templar.evaluate(Templar.scala:403)
        at net.verdagon.vale.driver.Driver$.build(Driver.scala:144)
        at net.verdagon.vale.driver.Driver$.build(Driver.scala:89)
        at net.verdagon.vale.driver.Driver$.buildAndOutput(Driver.scala:169)
        at net.verdagon.vale.driver.Driver$.main(Driver.scala:248)
        at net.verdagon.vale.driver.Driver.main(Driver.scala)

The error doesn't indicate to me on which line it occurred, or what the error really is.
I find it a bit strange that the interface refers to Human:

interface Bipedal {
  fn hop(s &Human) void;
  fn skip(s &Human) void;
}

but should also work for any other struct that has hop and skip functions, &Darkelf cannot possibly match &Human ?

Note: The same or very similar error is shown at compilation for the Example in section Limitations of Interfaces on page https://vale.dev/guide/generics

**Comment by Ivo-Balbaert** [comment]
The new example in the section Using Interfaces in the Guide page https://vale.dev/guide/interfaces compiles and works in v 0.1.1 ! Closing the issue.
